dataSources:
- !!org.apache.commons.dbcp2.BasicDataSource
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/shard01?autoReconnect=true
  username: shard01
  password: shard01
  maxTotal: 30
- !!org.apache.commons.dbcp2.BasicDataSource
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/shard02?autoReconnect=true
  username: shard02
  password: shard02
  maxTotal: 30

shardingTable:
- tableName: user
  shardingColumn: userid
  shardingMethod: CRC32

broadcastTable: [config]